### ISSUE TITLE
Wrong tempo displayed

### ISSUE THREAD

**Issue by Thiago-Morais** [lgvr123/musescore-taptempo#2]
The Tempo displayed is always half the bpm. The correct value is only achieved if a half note is selected.
Example:
Tapping at 120bpm displays 60 regardless of the selected note duration
Also, changing the note duration does nothing to the actual value. It just changes the symbol written on the sheets.
I believe changing the note on the plugin should convert the bpm to that note value using quarter notes as the base value.
Intended example:
- half note and 120bpm selected writes "half note = 240"
- quarter note and 80bpm selected writes "quarter note = 80"
- eighth note and 200bpm selected writes "eighth note = 50"

**Comment by lgvr123** [comment]
I'll check. Thanks for reporting this.
Are you on MU4.x or MU3.6.2/3.7 ?

**Comment by lgvr123** [comment]
Hi, I can reproduce it in MU4.2.1 and MU3.7, but not exactly how you describe it.
The fact the is MU seems not able (in those versions) to react fast enough on the button click above +-100bpm.
I can see it in the logs.
If in MU3.6.2, I do 8 clicks at 150bpm, the plugin handles 8 clicks.
If in MU3.7, I do 8 clicks at 150bpm, the plugin does only handles 4-5 clicks. And hence is not able to count the right tempo.
I will bring that to the MU4 repository and to the MU3.7 repository.

**Comment by Thiago-Morais** [comment]
> Are you on MU4.x or MU3.6.2/3.7 ?
I'm using 4.2.1, but I remember this happening in 4.1.1 as well

**Comment by Thiago-Morais** [comment]
> Are you on MU4.x or MU3.6.2/3.7 ?

I'm using 4.2.1, but I remember this happening in 4.1.1 as well

**Comment by lgvr123** [comment]
For the record:
* [Issue in 4.2.1](https://github.com/musescore/MuseScore/issues/21303)
* [Issue in 3.7](https://github.com/Jojo-Schmitz/MuseScore/issues/298)

**Comment by lgvr123** [comment]
Solved for MU4.x with [release 1.2.3](https://github.com/lgvr123/musescore-taptempo/releases/tag/1.2.3).
Unsolved for MU3.7

**Comment by lgvr123** [comment]
New version [1.2.4](https://github.com/lgvr123/musescore-taptempo/releases/tag/1.2.4) solving this issue, compatible with MU3.6.2, MU3.7 and MU4.x
