### ISSUE TITLE
Plugin broken on 4.4 update

### ISSUE THREAD

**Issue by Thiago-Morais** [lgvr123/musescore-taptempo#3]

**Comment by lgvr123** [comment]
Thanks for notifying me. This occurred because the MuseScore devteam made some drastic change in that version leading to 90% of the plugin no longer working.
I'll update this plugin some day. But definitively not now.

**Comment by lgvr123** [comment]
Hi, I updated the plugin. There is now a specific version for MU4.4: taptempo44.qml
